### PR TITLE
(improve) Elements

### PR DESCRIPTION
**Pull request by sneakyweasel**
- Added parameters to GlassSlab and VacuumJar
- Would be more convenient to use percentage parameter for attenuator
- Would be possible to use percentage to specify BeamSplitter transmission / reflection %
Tried to enforce your style, let me hear what you think!

### CODE REVIEW

**Comment by sneakyweasel** [comment]
Just checked Polarizer and phasePlate, 

- polarizer(angle: number, polarizationOrientation: number)
I am using the polarization orientation in angles to rotate the internal grid

- phasePlate(angle: number, polarizationOrientation: number, phase = 1 / 4)
Polarization orientation is also used for rotation of the internal grid
I can use percentage parameter for the phase

I guess we are getting close to having all our elements working ;p

**Comment by stared** [comment]
I see what you mean, but find the naming confusing.

`percentage` suggests 0 to 100. When it comes to things for which 0 = nothing, and 1 = full wavelength, I suggest `shifInLambda` or something in that line.

Vide https://www.edmundoptics.eu/knowledge-center/application-notes/optics/understanding-waveplates/, https://www.rp-photonics.com/waveplates.html, https://en.wikipedia.org/wiki/Quarter-wave_impedance_transformer.

**Comment by sneakyweasel** [comment]
absorber
This is the current variable absorber, it would be better to be able to specify percentage of absorption.

**Comment by sneakyweasel** [comment]
laser
Laser is currently taking 0 and 90 polarization (H, V)

**Pull request closed without merging**
