### PR TITLE
Build for browser with Rollup

### PR DESCRIPTION
**Pull request by stared**
Right now (`v0.4.0`) quantum tensors are npm-installable, but not work in a browser. 

I try to use [Rollup.js](https://rollupjs.org/) to make it universally installable. I have some issues with TypeScript types and [lodash](https://lodash.com/) dependency. I will see how it works.

I start with:

* https://medium.com/@ali.dev/how-to-publish-a-js-library-to-npm-with-rollup-typescript-8b51ede8f562

Looking at:

* https://stackoverflow.com/questions/41329876/generate-typescript-definition-files-using-rollup
* https://github.com/pixijs/pixi-filters/wiki/Rollup---TypeScript-Example
* https://github.com/team-innovation/vue-sfc-rollup/issues/35
* https://github.com/Wessberg/rollup-plugin-ts (and https://github.com/ali-kamalizade/text-select)

Right now it looks working-ish:

```
src/index.ts → dist/index.js, dist/index.esm.js, dist/index.min.js...
(!) Circular dependencies
src\Vector.ts -> src\Basis.ts -> src\Vector.ts
src\Vector.ts -> src\Basis.ts -> src\Operator.ts -> src\Vector.ts
src\Basis.ts -> src\Operator.ts -> src\Basis.ts
(!) Missing global variable name
Use output.globals to specify browser global variable names corresponding to external modules
lodash (guessing '_')
```

I will see if it works.

### CODE REVIEW

**Comment by stared** [comment]
Apparently, it does work (https://jsfiddle.net/stared/wusev5a9/):

image

Note that we need to add `lodash` manually.

**Comment by stared** [comment]
To do:

- [ ] change name so it is something like `quantum-tensors.min.js` (now it is https://unpkg.com/quantum-tensors@0.4.1/dist/index.min.js)
- [ ] do something with lodash dependency

**Comment by stared** [comment]
Or not, as after using in it `bra-ket-vue`, there is an error with `lodash`.

image

**Comment by stared** [comment]
With `v0.4.2` the same issue. Still, types work inside, but when I run `yarn serve` I get:

> quantum-tensors.min.js?040c:15 Uncaught ReferenceError: _ is not defined

Not sure why does it use `quantum-tensors.js` instead.

**Comment by stared** [comment]
@ardcore thanks!

I tried to publish & import it. In the browser, it still works.

However, in `bra-ket-vue` there is an error (after `yarn serve`), but a different one:

> serve-dev.vue?f0cf:12 Uncaught TypeError: Cannot read property 'emptySpace' of undefined

The code contains

```
import {
  Photons, Vector, Operator, Elements, Dimension, Cx, Gates, Circuit,
} from 'quantum-tensors';

const sizeX = 8;
const sizeY = 8;
const state = Photons.emptySpace(sizeX, sizeY)
```

The current version does not export `Photon` class (and most likely - other as well). Any hints why?

**Comment by ardcore** [comment]
@stared could you tell me in which branch of `bra-ket-vue` I could test this?

**Comment by stared** [comment]
@ardcore Related to this PR: https://github.com/Quantum-Game/bra-ket-vue/pull/26

**Comment by stared** [comment]
I removed `browser` field in `package.json`.
I checked that and it was indeed an unrelated error (TOFFOLI gate).

Now it works both for browser and as an npm package (as tested in bra-ket-vue).

However, for some reason, when running build I get:

```
[!] (plugin rpt2) Error: EPERM: operation not permitted, rename 'C:\Users\pmigd\my_repos\qg2\quantum-tensors\node_modules\.cache\rollup-plugin-typescript2/rpt2_2280d27ef5907dd577c43fbb76a9c3c81ceaedad/code/cache_' -> 'C:\Users\pmigd\my_repos\qg2\quantum-tensors\node_modules\.cache\rollup-plugin-typescript2/rpt2_2280d27ef5907dd577c43fbb76a9c3c81ceaedad/code/cache'
Error: EPERM: operation not permitted, rename 'C:\Users\pmigd\my_repos\qg2\quantum-tensors\node_modules\.cache\rollup-plugin-typescript2/rpt2_2280d27ef5907dd577c43fbb76a9c3c81ceaedad/code/cache_' -> 'C:\Users\pmigd\my_repos\qg2\quantum-tensors\node_modules\.cache\rollup-plugin-typescript2/rpt2_2280d27ef5907dd577c43fbb76a9c3c81ceaedad/code/cache'
    at Object.renameSync (fs.js:675:3)
    at RollingCache.roll (C:\Users\pmigd\my_repos\qg2\quantum-tensors\node_modules\rollup-plugin-typescript2\src\rollingcache.ts:101:3)
    at TsCache.done (C:\Users\pmigd\my_repos\qg2\quantum-tensors\node_modules\rollup-plugin-typescript2\src\tscache.ts:195:18)
    at Object._ongenerate (C:\Users\pmigd\my_repos\qg2\quantum-tensors\node_modules\rollup-plugin-typescript2\src\index.ts:315:12)
    at Object.generateBundle (C:\Users\pmigd\my_repos\qg2\quantum-tensors\node_modules\rollup-plugin-typescript2\src\index.ts:278:9)
    at C:\Users\pmigd\my_repos\qg2\quantum-tensors\node_modules\rollup\dist\shared\rollup.js:17408:25
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Manual removing `lib`  and `dist` folders help.

**Pull request merged**
